---
title: "HW3"
author: "Qi Qi"
date: "9/20/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


1.

$$f(x_i;\theta)=\frac{1}{\pi [1+(x_i-\theta)^2]}$$
$$\ell=\sum_{i=1}^{n}logf(X_i;\theta)=\sum_{i=1}^{n}-log(\pi[1+(X_i-\theta)^2])=-nlog\pi-\sum_{i=1}^{n}log[1+(X_i-\theta)^2]$$
$$\ell'=\frac{\partial \ell}{\partial \theta}=-\sum_{i=1}^{n}\frac{2\theta-2X_i}{1+(X_i-\theta)^2}=-2\sum_{i=1}^{n}\frac{\theta-X_i}{1+(X_i-\theta)^2}$$
$$\ell''=\frac{\partial \ell'}{\partial \theta}=-2\sum_{i=1}^{n}\frac{1+(X_i-\theta)^2-2(\theta-X_i)^2}{[1+(X_i-\theta)^2]^2}=-2\sum_{i=1}^{n}\frac{1-(X_i-\theta)^2}{[1+(X_i-\theta)^2]^2}$$
$$I_{n}(\theta)=nE[(\frac{\partial logf(x;\theta)}{\partial \theta})^2]=nE[\frac{4(X-\theta)^2}{[1+(X-\theta)^2]^2}]=4n\int_R\frac{(x-\theta)^2}{[1+(x-\theta)^2]^2}\frac{1}{\pi [1+(x-\theta)^2]}dx$$
$$=4n\int_R\frac{x^2}{[1+x^2]^2}\frac{1}{\pi [1+x^2]}dx=\frac{4n}{\pi}\int_R\frac
{x^2}{(1+x^2)^3}dx=\frac{8n}{\pi}\int_0^{\infty}\frac
{x^2}{(1+x^2)^3}dx$$

Let $y=\frac{1}{1+x^2}$, then $x=(\frac{1}{y}-1)^{1/2}$, $dx=-\frac{1}{2}(\frac{1}{y}-1)^{-1/2}y^{-2}dy$.
$$I_n(\theta)=\frac{8n}{\pi}\int_1^0(\frac{1}{y}-1)y^3(-\frac{1}{2})(\frac{1}{y}-1)^{-1/2}y^{-2}dy$$
$$=\frac{4n}{\pi}\int_0^1y^{1/2}(1-y)^{1/2}dy=\frac{4n}{\pi}\frac{\Gamma(3/2)\Gamma(3/2)}{\Gamma(3)}=\frac{4n}{\pi}\frac{(\frac{1}{2}\pi)^2}{2!}=\frac{n}{2}$$

2. 

Loglikelihood function and plot:

```{r}
set.seed(20180909)

loglik <- function(theta,x) sum(-log(pi) - log(1 + (x - theta)^2))
theta<- 5
x<- rcauchy(10, 5, 1)
plot(theta,sapply(theta,loglik,x),ylab="LogL of Cauchy")
```

3.

Iteration:
```{r}
g <- function(theta) sum(2 * (x - theta)/(1 + (x - theta)^2))
dg <- function(theta) sum((2 * (x - theta)^2 - 2)/(1 + (x - theta)^2)^2)
newton<- function(fun, dfun, x0, eps, maxit){
  for (i in 1:maxit) {
    x1 <- x0 - fun(x0) / dfun(x0)
    if (abs(x1 - x0) < eps || abs(fun(x1)) < eps){
      return(NA)
    } 
    x0 <- x1
  }
  return(x1)
}

init <- seq(-10, 20, by = 0.5)
sapply(init, function(x) newton(g, dg, x, 1e-6, 1000))
```

We can see the iteration returns three different results with different initial values.

4.
```{r}
f1<- function(theta) sum(2 * (x - theta)/(1 + (x - theta)^2))+ theta
f2<- function(theta) 0.64 * sum(2 * (x - theta)/(1 + (x - theta)^2))+ theta
f3<- function(theta) 0.25 * sum(2 * (x - theta)/(1 + (x - theta)^2))+ theta

fixed<- function(fun, x0, eps, maxit){
  for (i in 1 : maxit){
    x1<- fun(x0)
    if (abs(x1-x0)< eps){
      return(NA)
    }
     x0 <- x1
  }
  return(x1)
}

init <- seq(-10, 20, by = 0.5)
sapply(init, function(x) fixed(f1, x, 1e-6, 1000))
init <- seq(-10, 20, by = 0.5)
sapply(init, function(x) fixed(f2, x, 1e-6, 1000))
init <- seq(-10, 20, by = 0.5)
sapply(init, function(x) fixed(f3, x, 1e-6, 1000))

```

5.

```{r}
g <- function(theta) sum(2 * (x - theta)/(1 + (x - theta)^2))

newtons<- function(fun, x0, eps, maxit){
  for (i in 1 : maxit){
    x1<- x0 + 2 * fun(x0)/ length(x)
    if (abs(x1 - x0)< eps||abs(fun(x1)) < eps){
      return(NA)
    }
    x0 <- x1
  }
  return(x1)
}

init <- seq(-10, 20, by = 0.5)
sapply(init, function(x) newtons(g, x, 1e-6, 1000))
```
